# Generated by Django 3.1.1 on 2020-10-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='language',
            field=models.CharField(choices=[('pl', 'Polski'), ('en', 'English')], max_length=2),
        ),
    ]
