# Generated by Django 3.1.1 on 2020-10-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_auto_20201002_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='landing_page',
            field=models.BooleanField(default=False),
        ),
    ]
