# Generated by Django 3.0.7 on 2023-01-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_site_landing_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='theme',
            field=models.CharField(choices=[('massively', 'massively'), ('hyde', 'hyde'), ('poole', 'poole')], max_length=50),
        ),
    ]
